### ISSUE TITLE
Aluminum Y gantry stl files

### ISSUE THREAD

**Issue by vanatd** [VzBoT3D/VzBoT-Vz330#44]
Hello there!
First of all, thank you for your hard work! it looks amazing!

I was looking through the GitHub repo and did not find the STL file for the aluminum y gantry. Idk maybe you did not push it on purpose, but it would be very cool to have it. 

Thank you in advance!

**Comment by vanatd** [comment]
Seems like there are no stl files for the main parts in aluminum at all :( 
Is there a way to use printed stl files for the CNC machine?

**Comment by chrishenze** [comment]
Hi man,
Unfortunately the aluminum parts are not open source. We decided against releasing them because a lot of effort and work went into developing and testing this hardware to get it to the point it is now. Buying products from Aluminum Parts directly supports our efforts to further develop the VZBot and bring you complete kits and cool new LSDs. We also had our fare share of problems with cheap chinese copies in that regard.

**Comment by vanatd** [comment]
Thanks a lot for your response! 
Unfortunately I can't buy it in Ukraine so far. 
Anyway, you did a very cool and hard job, thanks a lot for doing that!
once I can buy these parts I definitely will do it!
